on:
  push:
    tags:
      - '**'

jobs:
  tagged-release-latest:
    name: "Tagged Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          git config --global --add safe.directory /github/workspace
          pip install -r requirements.txt
          make bundle OPTS='--strip-etags --crush-floats'
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: "This is the latest release of Ty's levels."
          make_latest: true
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          files: |
            *.zip
